project 'JHNetworkModule.xcodeproj'

# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'
  inhibit_all_warnings!
target 'JHNetworkModule' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for JHNetworkModule
  #网络请求以及封装
   pod 'AFNetworking' 
  #JSON数据解析
#   pod 'JSONModel'
   pod 'YYModel'
end
